#!/bin/sh  
#PBS -N obscore_%JTYP%_prep_%PDY%_%CC%_%DESC%
#PBS -j oe
#PBS -q dev               
#PBS -l walltime=00:20:00 
#PBS -A OBSPROC-DEV
##PBS -l place=vscatter,select=1:ncpus=4:mem=180gb:prepost=true
#PBS -l place=vscatter,select=1:ncpus=16:mem=520gb:prepost=true
#PBS -l debug=true

##############################################
# Submit notes:
# Run from [ps]tmp when running manually
# When running from cron, output is written to /u/$USER. Bottom of trigger mv's to stmp
# For specific PDY:
# > jtyp=gdas cyc=00 PDY=20170126 desc=somethingfun /u/iliana.genkova/bin/cycqsub /path/to/triggers/jglobal_prep.wc2.pbs
# For latest/current PDY:
# > jtyp=gdas cyc=00 desc=somethingfun /u/iliana.genkova/bin/cycqsub /path/to/triggers/jglobal_prep.wc2.pbs
# cycqsub location: /u/iliana.genkova/bin 
##############################################

set -xu

export envir=prod
export cyc=%CC%
DESC=%DESC%
JTYP=%JTYP%
export job=${JTYP}_prep_$cyc
export jobid=$job.$PBS_JOBID
export PDY=%PDY%

userROOT=/lfs/h2/emc/obsproc/noscrub/$USER

export obsNET=obscore
export obscore_ver=v1.3.0
export obscore_ver_pckg=v1.3.0
export prepobs_ver=1.2.0
PACKAGEROOTpara=/lfs/h1/ops/para/packages
#export HOMEobsproc=${PACKAGEROOTpara}/obsproc.${obsproc_ver_pckg}   # NCO para
#export HOMEobsproc=${PACKAGEROOT}/obsproc.${obsproc_ver_pckg}       # NCO prod
#export HOMEobsproc=${userROOT}/install/obsproc-rmprep          # SM local
#export HOMEobsproc=${userROOT}/GIT/play/obsproc.13                      # IG local
export HOMEobscore=${userROOT}/git/CORe/obscore

VERSION_FILE=${HOMEobscore}/versions/run.ver                     # NCO para&prod
#VERSION_FILE=${userROOT}/install/obsproc-rmprep/versions/run.ver # SM local
#VERSION_FILE=${userROOT}/GIT/play/obsproc/versions/run.ver             # IG local
if [ -f $VERSION_FILE ]; then
   . $VERSION_FILE
else
  echo Need version info...  Exiting...
 exit 7
fi

export prepobs_ver=1.2.0

#Load the modules
module load prod_envir/2.0.4
module load grib_util/${grib_util_ver}
module load netcdf/${netcdf_ver}
module load intel/${intel_ver}
module load craype/${craype_ver}
module load cray-mpich/${cray_mpich_ver}
module load cray-pals/${cray_pals_ver}
module load cfp/${cfp_ver}

#use para installation
module use /apps/ops/para/nco/modulefiles/compiler/intel/19.1.3.304
#use local installation
#module use ${userROOT}/install/bufr-dump/modulefiles                                   # SM local
#module use  ${userROOT}/GIT/bufr-dump/install/modulefiles # IG local
#module load bufr_dump/${bufr_dump_ver}

# use local prepobs installation
module unload prepobs
#module use ${userROOT}/install/prepobs/modulefiles            # SM local
#module use ${userROOT}/GIT/play/prepobs.13/install/modulefiles         # IG local
module use ${userROOT}/git/CORe/prepcore/install/modulefiles
module load prepobs/${prepobs_ver}


#Check if they exist
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)grib_util/") -eq 0 ]]; then echo "grib_util is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)netcdf/") -eq 0 ]]; then echo "netcdf is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)bufr_dump/") -eq 0 ]]; then echo "bufr_dump is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)prepobs/") -eq 0 ]]; then echo "prepobs is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)intel/") -eq 0 ]]; then echo "intel is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)craype/") -eq 0 ]]; then echo "craype is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)cray-mpich/") -eq 0 ]]; then echo "cray-mpich is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)cray-pals/") -eq 0 ]]; then echo "cray-pals is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)cfp/") -eq 0 ]]; then echo "cfp is not loaded!"; fi


export SENDECF=NO   # developer
export SENDSDM=NO   # developer
export SENDDBN=NO   # developer

export DATAROOT=/lfs/h2/emc/stmp/$USER
export jlogfile=/lfs/h2/emc/stmp/$USER/${JTYP}.$PDY.jlogfile

#export HOMEgfs=$PACKAGEROOT/gfs.v16.2.0 #no longer has /fix/prepobs_errtable.global but more /fix dirs
export HOMEgfs=$COMROOT/gfs/v16.3/       #NCO approved shared location for common GFS files

export COMIN_ROOT=/lfs/h2/emc/stmp/$USER/CRON/${DESC}/com
#export COMINgdas=/lfs/h1/ops/canned/com/gfs/v16.2/${JTYP}.${PDY}/${cyc}/${COMPONENT}
#export COMINgfs=/lfs/h1/ops/canned/com/gfs/v16.2/${JTYP}.${PDY}/${cyc}/${COMPONENT}
export COMOUT_ROOT=/lfs/h2/emc/stmp/$USER/CRON/${DESC}/com

#export DEBUG_LEVEL=3
#export KEEPDATA=YES
# try to speed up
export DEBUG_LEVEL=1
export KEEPDATA=NO

export LOUD=ON


$HOMEobscore/jobs/JOBSCORE_GLOBAL_PREP
err=$?

# When run from cron, the stdout is written to /u/$USER
# mv to stmp
pbsjobid=$(echo $PBS_JOBID | cut -d'.' -f1)
cronlogfile=/u/$USER/$PBS_JOBNAME.o$pbsjobid
outputdir=/lfs/h2/emc/stmp/${USER}/CRON/${DESC}/output
if [ -f "$cronlogfile" ]; then
  mkdir -p $outputdir
  mv $cronlogfile ${outputdir}/$PBS_JOBNAME.o$pbsjobid
fi

# Kick off prep_post job
if [ $err -eq 0 ]; then
  echo "submit jglobal_prep_post:"
  jtyp=$JTYP PDY=$PDY desc=$DESC bash -l /u/$USER/bin/cycpsub \
  ${userROOT}/Trigs.KEEP/renameGlobal/jcore_prep_post.wc2.pbs.R13 
  #/lfs/h2/emc/obsproc/noscrub/iliana.genkova/Trigs.KEEP/jglobal_prep_post.wc2.pbs
fi

exit

