#!/bin/sh  
#PBS -N obsproc_%JTYP%_dump_%PDY%_%CC%_%DESC%
#PBS -j oe
#PBS -S /bin/bash
#PBS -q dev
#PBS -l walltime=00:20:00
#PBS -A OBSPROC-DEV
#PBS -l place=vscatter,select=1:ncpus=14:mem=500gb
#PBS -l debug=true

##############################################
# Submit notes:%
# Run from [ps]tmp when running manually
# When running from cron, output is written to /u/$USER. Bottom of trigger mv's to stmp
# For specific PDY:
# > jtyp=[gdas][gfs] cyc=00 PDY=20170126 desc=somethingfun /u/iliana.genkova/bin/cycqsub /path/to/triggers/jglobal_dump.wc2.pbs
# For latest/current PDY:
# > jtyp=[gdas][gfs] cyc=00 desc=somethingfun /u/iliana.genkova/bin/cycqsub /path/to/triggers/jglobal_dump.wc2.pbs
# cycqsub location: /u/iliana.genkova/bin 
##############################################

set -xu

export envir=prod

export cyc=%CC%
DESC=%DESC%
JTYP=%JTYP%
export job=${JTYP}_dump_$cyc
export jobid=$job.$PBS_JOBID
export PDY=%PDY%

userROOT=/lfs/h2/emc/obsproc/noscrub/$USER

export obsproc_ver=v5.0
export obsproc_ver_pckg=v1.2.1
export NET=obsproc
#PACKAGEROOTpara=/lfs/h1/ops/para/packages
#export HOMEobsproc=${PACKAGEROOTpara}/obsproc.${obsproc_ver_pckg}   # NCO para
#export HOMEobsproc=${PACKAGEROOT}/obsproc.${obsproc_ver_pckg}        # NCO prod
#export HOMEobsproc=${userROOT}/install/obsproc-rel.v1.0.0      # SM local
export HOMEobsproc=${userROOT}/GIT/play/obsproc.G             # IG local  

VERSION_FILE=$HOMEobsproc/versions/run.ver                            # NCO prod
#VERSION_FILE=${userROOT}/install/obsproc-rel.v1.0.0/versions/run.ver # SM local
#VERSION_FILE=${userROOT}/GIT/obsproc/versions/run.ver        # IG local
if [ -f $VERSION_FILE ]; then
   . $VERSION_FILE
else
  echo Need version info...  Exiting...
 exit 7
fi

#already in versioins/run.ver :)
export bufr_dump_ver=5.0.0 #1.0.0

# Load the modules specified in $VERSION_FILE
module load libjpeg
module load grib_util/${grib_util_ver}
module load netcdf/${netcdf_ver}
# use para installation
#module use /apps/ops/para/nco/modulefiles/compiler/intel/19.1.3.304 
#module use ${userROOT}/install/bufr-dump/modulefiles
#module unload bufr_dump/${bufr_dump_ver}
#module use ${userROOT}/GIT/play/bufr-dump.ATMS_VIIRS/install/modulefiles 
#module load bufr_dump/${bufr_dump_ver}
#echo LOADED ILIANA bufr-dump
#module use ${userROOT}/GIT/prepobs/install/modulefiles
module load intel/${intel_ver}
module load craype/${craype_ver}
module load cray-mpich/${cray_mpich_ver}
module load cray-pals/${cray_pals_ver}
module load cfp/${cfp_ver}


module unload bufr_dump
module use ${userROOT}/GIT/play/bufr-dump.G/install/modulefiles
module load bufr_dump/${bufr_dump_ver}
echo LOADED ILIANA bufr-dump
echo $BUFR_DUMPLIST

# Be sure the modules are loaded 
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)prod_util/") -eq 0 ]]; then echo "prod_util is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)prod_envir/") -eq 0 ]]; then echo "prod_envir is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)libjpeg/") -eq 0 ]]; then echo "libjpeg is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)grib_util/") -eq 0 ]]; then echo "grib_util is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)netcdf/") -eq 0 ]]; then echo "netcdf is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)bufr_dump/") -eq 0 ]]; then echo "bufr_dump is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)intel/") -eq 0 ]]; then echo "intel is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)craype/") -eq 0 ]]; then echo "craype is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)cray-mpich/") -eq 0 ]]; then echo "cray-mpich is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)cray-pals/") -eq 0 ]]; then echo "cray-pals is not loaded!"; fi
if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)cfp/") -eq 0 ]]; then echo "cfp is not loaded!"; fi


export SENDECF=NO   # developer
export SENDDBN=NO   # developer
export SENDSDM=NO   # developer

export TANK=$DCOMROOT
export TANK_004030=/lfs/h1/ops/dev/dcom #Windborne and Sorcerer Feb11, obs as of 16z
export TANK_002102=/lfs/h1/ops/dev/dcom/ # 002103->002101->002102 dev uprair from ship, to catch Urban sky, as of 20260220 00z 

#export TANK_001103=/lfs/h1/ops/dev/dcom  #NDBC buoys in BUFR have HSMSL (think GL,M.Morris)

#export TANK_002101=/lfs/h1/ops/dev/dcom/ # 002103->002101dev uprair from ship, to catch Urban sky

# GMI tanks are in prod already June 2022
#export TANK_021246=/lfs/h2/emc/obsproc/noscrub/ashley.stanfield/git/TANK_DUMP #${userROOT}/DCOMDIR/TEST/prod/

#export EPRM=${userROOT}/sample_sdmedit.txt
#export EPRM=/lfs/h2/emc/obsproc/noscrub/iliana.genkova/SDMEDIT/sample_sdmedit.txt

export DATAROOT=/lfs/h2/emc/stmp/$USER 
export jlogfile=/lfs/h2/emc/stmp/$USER/${JTYP}.$PDY.jlogfile

export COMOUT_ROOT=${DATAROOT}/CRON/${DESC}/com
export COMPONENT=atmos

export DEBUG_LEVEL=3
export LOUD=on #ON
export KEEPDATA=YES


$HOMEobsproc/jobs/JOBSPROC_GLOBAL_DUMP #slow jobs
err=$?

# When run from cron, the stdout is written to /u/$USER
# mv to stmp
pbsjobid=$(echo $PBS_JOBID | cut -d'.' -f1)
cronlogfile=/u/$USER/$PBS_JOBNAME.o$pbsjobid
outputdir=/lfs/h2/emc/stmp/${USER}/CRON/${DESC}/output
if [ -f "$cronlogfile" ]; then
  mkdir -p $outputdir
  mv $cronlogfile ${outputdir}/$PBS_JOBNAME.o$pbsjobid
fi

# ... existing Script A code ...
if [ $err -eq 0 ]; then
    touch /lfs/h2/emc/stmp/${USER}/${JTYP}_dump_done.txt
    # Check if B is already done
   #try with the where* files, hoping $COMOUT is exported from the job run above!!!!!!!!!!!! 
   #if [ -f $COMOUT/where_${cycle}_${RUN}_dump2_ran]; then
    if [ -f /lfs/h2/emc/stmp/${USER}/${JTYP}_dump2_done.txt ]; then
        echo "A finished last. Triggering Script C."
        echo "submit jglobal_dump_post"
  jtyp=$JTYP PDY=$PDY desc=$DESC bash -l /u/$USER/bin/cycqsub \
  ${userROOT}/Trigs.KEEP/jglobal_dump_post.wc2.pbs.G

        # Clean up flags for the next run
        rm -f /lfs/h2/emc/stmp/${USER}/${JTYP}_*_done.txt
    fi
fi

exit #!!!!!!!!!!!!!!!!

# Kick off dump2 job
if [ $err -eq 0 ]; then
        #if [ $err2 -eq 0 ]; then
  echo "submit jglobal_dump2_post"
  jtyp=$JTYP PDY=$PDY desc=$DESC bash -l /u/$USER/bin/cycqsub \
  ${userROOT}/Trigs.KEEP/jglobal_dump2_post.wc2.pbs.G
  #/lfs/h2/emc/obsproc/noscrub/iliana.genkova/Trigs.KEEP/jglobal_dump_post.wc2.pbs
        #fi  # WILL err1 be exported and kept in the memomry if it's a separate job in the queue?
fi

# Kick off dump_post job
if [ $err -eq 0 ]; then
	#if [ $err2 -eq 0 ]; then    
  echo "submit jglobal_dump_post"
  jtyp=$JTYP PDY=$PDY desc=$DESC bash -l /u/$USER/bin/cycqsub \
  ${userROOT}/Trigs.KEEP/jglobal_dump_post.wc2.pbs.G 
  #/lfs/h2/emc/obsproc/noscrub/iliana.genkova/Trigs.KEEP/jglobal_dump_post.wc2.pbs
        #fi  # WILL err1 be exported and kept in the memomry if it's a separate job in the queue?
fi

# Kick off prep job
if [ $err -eq 0 ]; then
  echo "submit jglobal_prep"
  jtyp=$JTYP PDY=$PDY desc=$DESC bash -l /u/$USER/bin/cycqsub \
  ${userROOT}/Trigs.KEEP/jglobal_prep.wc2.pbs.G
  #/lfs/h2/emc/obsproc/noscrub/iliana.genkova/Trigs.KEEP/jglobal_prep.wc2.pbs
fi

exit
